
#New Config
[Back]
	enable = true
	enable-on-death = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 30
	aliases = ["back", "return"]
	#Range: > 0
	cost = 0

[Bal]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	other-perm = "serverutils.bal-other"
	aliases = ["bal"]
	#Range: > 0
	cost = 0
	#Range: > 0
	other-cost = 0

[Bomb]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["bomb", "boom"]
	#Range: > 0
	cost = 0

[Broadcast]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["broadcast"]
	#Range: > 0
	cost = 0

[Bypass]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["bypass"]
	#Range: > 0
	cost = 0

[ChestShop]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	max-perm = "serverutils.maxshops."
	adminperm = "serverutils.chestshop.createadmin"
	aliases = ["chestshop"]
	#Range: > 0
	cost = 0

[Claim]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	max-perm = "serverutils.maxclaims_"
	load-perm = "serverutils.maxclaimsload_"
	load-offline = "serverutils.claimloadoffline"
	bypass-perm = "serverutils.claim-bypass"
	aliases = ["claim"]
	#Range: > 0
	cost = 0

[Claimflag]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["claimflag"]
	#Range: > 0
	cost = 0

[Clearlag]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["clearlag"]
	#Range: > 0
	cost = 0

[Delhome]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["delhome"]
	#Range: > 0
	cost = 0

[Delwarp]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["delwarp"]
	#Range: > 0
	cost = 0

[Econ]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["econ"]
	#Range: > 0
	cost = 0

[Endchest]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["endchest", "ec"]
	#Range: > 0
	cost = 0

[Feed]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	other-perm = "serverutils.feed.other"
	aliases = ["feed"]
	#Range: > 0
	cost = 0

[Flood]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["drown"]
	#Range: > 0
	cost = 0

[Fly]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	other-perm = "serverutils.fly.other"
	aliases = ["fly"]
	#Range: > 0
	cost = 0

[Gamemode]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["gamemode", "gm"]
	#Range: > 0
	cost = 0

[God]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	other-perm = "serverutils.god.other"
	aliases = ["god", "tgm"]
	#Range: > 0
	cost = 0

[Heal]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	other-perm = "serverutils.heal.other"
	aliases = ["heal"]
	#Range: > 0
	cost = 0

[Home]
	enable = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 0
	home-max-perm = "serverutils.maxhome_"
	aliases = ["home"]
	#Range: > 0
	cost = 0

[Homes]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["homes"]
	#Range: > 0
	cost = 0
	other-perm = "command.homes.other"

[Invsee]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["invsee"]
	#Range: > 0
	cost = 0

[Item]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["item"]
	#Range: > 0
	cost = 0

[Jail]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["jail"]
	#Range: > 0
	cost = 0

[Kit]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	"modfiy perm" = "serverutils.kit.modify"
	aliases = ["kit"]
	#Range: > 0
	cost = 0

[Link]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["link"]
	#Range: > 0
	cost = 0

[Msg]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["message", "pm", "msg"]
	#Range: > 0
	cost = 0

[Msgtoggle]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["msgtoggle"]
	#Range: > 0
	cost = 0

[Motd]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	modify-perm = "serverutils.motd.modify"
	aliases = ["motd"]
	#Range: > 0
	cost = 0

[Mute]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["mute"]
	#Range: > 0
	cost = 0

[Nick]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	other-perm = "serverutils.nick.other"
	aliases = ["nickname", "nick"]
	#Range: > 0
	cost = 0

[Pay]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["pay"]
	#Range: > 0
	cost = 0

[Permission]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["permission", "perms", "p"]
	#Range: > 0
	cost = 0

[Price]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["price"]
	#Range: > 0
	cost = 0

[Rank]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	modify-perm = "serverutils.rank.modify"
	aliases = ["rank"]
	#Range: > 0
	cost = 0

[Rankup]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["rankup"]
	#Range: > 0
	cost = 0

[Reload]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 5
	aliases = ["sureload"]
	#Range: > 0
	cost = 0

[Repair]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 5
	"repair all perm" = "serverutils.repair.all"
	aliases = ["repair"]
	#Range: > 0
	cost = 0

[Respond]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["r"]
	#Range: > 0
	cost = 0

[Rtp]
	enable = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 0
	aliases = ["rtp"]
	#Range: > 0
	max = 5000
	#Range: > -2147483648
	origin_x = 0
	#Range: > -2147483648
	origin_z = 0
	#Range: > 0
	cost = 0

[Rtpfar]
	enable = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 0
	aliases = ["rtpfar"]
	#Range: > 0
	max = 10000
	#Range: > 0
	cost = 0

[Rtpnear]
	enable = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 0
	aliases = ["rtpnear"]
	#Range: > 0
	min = 100
	#Range: > 0
	max = 1000
	#Range: > 0
	cost = 0

[Rules]
	enable = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 0
	aliases = ["rules"]
	#Range: > 0
	cost = 0

[Sell]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["sell"]
	#Range: > 0
	cost = 0

[Sethome]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["sethome"]
	#Range: > 0
	cost = 0

[Setspawn]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["setspawn"]
	#Range: > 0
	cost = 0

[Setwarp]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["setwarp"]
	#Range: > 0
	cost = 0

[Smite]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["smite"]
	#Range: > 0
	cost = 0

[Spawn]
	enable = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 0
	aliases = ["spawn"]
	#Range: > 0
	cost = 0

[StaffChat]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["staffchat", "sc"]
	#Range: > 0
	cost = 0

[Sudo]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["sudo"]
	#Range: > 0
	cost = 0

[Titles]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["titles"]
	#Range: > 0
	cost = 0
	admin = "command.title.admin"

[Tpa]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	#Range: > 0
	"tp time" = 5
	aliases = ["tpa", "call"]
	#Range: > 0
	cost = 0

[TpaAccept]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["tpaccept"]
	#Range: > 0
	cost = 0

[TpaDeny]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["tpdeny"]
	#Range: > 0
	cost = 0

[TpaHere]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["tpahere"]
	#Range: > 0
	cost = 0

[Trust]
	enable = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 0
	aliases = ["trust"]
	#Range: > 0
	cost = 0

[Unclaim]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["unclaim"]
	#Range: > 0
	cost = 0

[UnclaimAll]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["unclaimall"]
	#Range: > 0
	cost = 0

[Unjail]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["unjail", "pardon"]
	#Range: > 0
	cost = 0

[Untrust]
	enable = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 0
	aliases = ["untrust"]
	#Range: > 0
	cost = 0

[Vote]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["vote", "votes"]
	#Range: > 0
	cost = 0

[Warp]
	enable = true
	#Range: > 0
	delay = 5
	#Range: > 0
	cooldown = 0
	aliases = ["warp"]
	#Range: > 0
	cost = 0

[Warps]
	enable = true
	#Range: > 0
	delay = 0
	#Range: > 0
	cooldown = 0
	aliases = ["warps"]
	#Range: > 0
	cost = 0

