#The tag used by the mod, leave empty for no tag.
tag = "&8[&9S&aU&8]"
#enabling global permissions will attempt to change all commands to use permissions generated dynamically by ServerUtils. If disabled, only the commands from ServerUtils will have the permissions.
"global perms" = true
#disabling translations will force all messages to be in english.
translations = true
#enabling this will allow you to run a discord bot that will bridge the server with discord. be sure to edit the discord config.
"discord bot" = false

["Welcome Message"]
	enabled = true
	#{player} will be replaced with the player name.
	text = "&hWelcome {player}&h to the server!"

["Goodbye Message"]
	enabled = true
	#{player} will be replaced with the player name.
	text = "&hGoodbye {player}"

#enabling the economy will apply the cost for commands, and other money related features.
[Economy]
	economy = false

	[Economy.Currency]
		singular = "Dollar"
		plural = "Dollars"
		symbol = "$"

[Voting]
	"enable voting" = false

["Auto Clearlag"]
	enabled = false
	#Clearlag Frequency requires a restart to apply
	#Range: > 0
	frequency = 5

	["Auto Clearlag".Entities]
		item = true
		passive = true
		hostile = true

["Color Chat"]
	perm = "serverutils.colorchat"
	link-perm = "serverutils.linkchat"
	enabled = true

	["Color Chat"."Command Help"]
		#KEY will be replaced with the sub command, and VALUE will be replaced with the info about the sub command.
		entry-format = "&8[&9KEY&8]&7:&aVALUE"
		#INFO will be replaced with the info about a command.
		info-format = "&bINFO"
		spacer-format = "&6===================="

	["Color Chat"."Color Codes"]
		#This will enable the &g color code, which will change text to rainbow.
		"rainbow enabled" = true
		#This will enable the &h color code, which will change text based on the month it is.
		"holiday enabled" = true

		["Color Chat"."Color Codes"."Holiday Colors"]
			January = "876f"
			February = "fd5c"
			March = "2af6"
			April = "ba9f"
			May = "aeb9"
			June = "7fc"
			July = "cf9"
			August = "6ca"
			September = "8ce"
			October = "86f"
			November = "c6e"
			December = "afc"

	["Color Chat"."Staff Chat"]
		#Formatting for the staff chat. Uses just the formatting codes. Don't include the &
		"staff tag" = "&3&l[STAFF]&r"
		#Formatting for the staff chat. Uses just the formatting codes. Don't include the &
		formatting = "bl"
		#Formatting for the staff chat. Uses just the formatting codes. Don't include the &
		"jail tag" = "&8&o[JAIL]"
		#Jail Formatting for the staff chat. Uses just the formatting codes. Don't include the &
		"jail formatting" = "7o"

#Jail Configs
[Jails]
	#A list of commands that can/can't be used while jailed.
	commands = [""]
	#If true, the commands listed will be allowed, if false then they will not be allowed.
	whitelist = false
	#This is the max distance (in blocks) that the jailed player can travel before being teleported back to the jail.
	#Range: > 0
	"max distance" = 10
	#Sets how jailed players are damaged. 0 will leave it normal, 1 will make the damage they take be 0, 2 will prevent them from taking any damage
	#Range: 0 ~ 2
	"player protection" = 1

