
#Emerald Tool Material
[emerald_tool_material]
	#Emerald Tool Durability [250-3000, default: 700]
	#Range: 250 ~ 3000
	emeraldToolDurability = 700
	#Emerald Tool efficiency [1.0-7.0, default: 5.5]
	#Range: 0.0 ~ 7.0
	emeraldToolEfficiency = 5.5
	#Emerald attack damage [1-40, default: 3.0]
	#Range: 0.0 ~ 40.0
	emeraldAttackDamage = 3.0
	#Emerald tool enchantability [1-30, default: 21]
	#Range: 1 ~ 30
	emeraldEnchantability = 21

#Ruby Tool Material
[ruby_tool_material]
	#Ruby Tool Durability [250-3000, default: 1050]
	#Range: 250 ~ 3000
	emeraldToolDurability = 1050
	#Ruby Tool efficiency [1.0-7.0, default: 6.5]
	#Range: 0.0 ~ 7.0
	emeraldToolEfficiency = 6.5
	#Ruby attack damage [1-40, default: 4.0]
	#Range: 0.0 ~ 40.0
	emeraldAttackDamage = 4.0
	#Ruby tool enchantability [1-30, default: 25]
	#Range: 1 ~ 30
	emeraldEnchantability = 25
	#Enable extra loot drops from Ruby Swords [true / false]
	rubySwordExtraLoot = false

#Obsidian Tool Material
[obsidian_tool_material]
	#Obsidian Tool Durability [250-3000, default: 525]
	#Range: 250 ~ 3000
	obsidianToolDurability = 525
	#Obsidian Tool efficiency [1.0-7.0, default: 5.5]
	#Range: 0.0 ~ 7.0
	obsidianToolEfficiency = 5.5
	#Obsidian attack damage [1-40, default: 3.0]
	#Range: 0.0 ~ 40.0
	obsidianAttackDamage = 3.0
	#Obsidian tool enchantability [1-30, default: 18]
	#Range: 1 ~ 30
	obsidianEnchantability = 18

#Copper Tool Material
[copper_tool_material]
	#Copper Tool Durability [250-3000, default: 225]
	#Range: 200 ~ 3000
	copperToolDurability = 225
	#Copper Tool efficiency [1.0-7.0, default: 5.5]
	#Range: 0.0 ~ 7.0
	copperToolEfficiency = 5.5
	#Copper attack damage [1-40, default: 3.0]
	#Range: 0.0 ~ 40.0
	copperAttackDamage = 3.0
	#Copper tool enchantability [1-30, default: 18]
	#Range: 1 ~ 30
	copperEnchantability = 18

#Amethyst Tool Material
[amethyst_tool_material]
	#Amethyst Tool Durability [250-3000, default: 1404]
	#Range: 250 ~ 3000
	amethystToolDurability = 1404
	#Amethyst Tool efficiency [1.0-7.0, default: 6.8]
	#Range: 0.0 ~ 7.0
	amethystToolEfficiency = 6.8
	#Amethyst attack damage [1-40, default: 5.0]
	#Range: 0.0 ~ 40.0
	amethystAttackDamage = 5.0
	#Amethyst tool enchantability [1-30, default: 25]
	#Range: 1 ~ 30
	amethystEnchantability = 25

#Emerald Armor Material
[emerald_armor_material]
	#Emerald armor durability multiplier [1-50, default: 31]
	#Range: 1 ~ 50
	emeraldArmorDurabilityMultiplier = 31
	#Emerald armor enchantability [1-31, default: 15]
	#Range: 1 ~ 31
	emeraldArmorEnchantability = 15
	#Emerald armor toughness [0.0-4.0, default: 0.0]
	#Range: 0.0 ~ 4.0
	emeraldArmorToughness = 0.0
	#Emerald armor knockback resistance [0.0-4.0, default: 0.0]
	#Range: 0.0 ~ 4.0
	emeraldArmorKnockbackResistance = 0.0
	#Emerald armor protection head [1-50, default: 3]
	#Range: 1 ~ 50
	emeraldArmorProtectionHead = 3
	#Emerald armor protection body [1-50, default: 8]
	#Range: 1 ~ 50
	emeraldArmorProtectionBody = 8
	#Emerald armor protection leggings [1-50, default: 6]
	#Range: 1 ~ 50
	emeraldArmorProtectionLeggings = 6
	#Emerald armor protection feet [1-50, default: 3]
	#Range: 1 ~ 50
	emeraldArmorProtectionFeet = 3

#Ruby Armor Material
[ruby_armor_material]
	#Ruby armor durability multiplier [1-50, default: 33]
	#Range: 1 ~ 50
	rubyArmorDurabilityMultiplier = 33
	#Ruby armor enchantability [1-31, default: 17]
	#Range: 1 ~ 31
	rubyArmorEnchantability = 17
	#Ruby armor toughness [0.0-4.0, default: 0.5]
	#Range: 0.0 ~ 4.0
	rubyArmorToughness = 0.5
	#Ruby armor knockback resistance [0.0-4.0, default: 0.1]
	#Range: 0.0 ~ 4.0
	rubyArmorKnockbackResistance = 0.1
	#Ruby armor protection head [1-50, default: 3]
	#Range: 1 ~ 50
	rubyArmorProtectionHead = 3
	#Ruby armor protection body [1-50, default: 8]
	#Range: 1 ~ 50
	rubyArmorProtectionBody = 8
	#Ruby armor protection leggings [1-50, default: 6]
	#Range: 1 ~ 50
	rubyArmorProtectionLeggings = 6
	#Ruby armor protection feet [1-50, default: 3]
	#Range: 1 ~ 50
	rubyArmorProtectionFeet = 3

#Obsidian Armor Material
[obsidian_armor_material]
	#Obsidian armor durability multiplier [1-50, default: 29]
	#Range: 1 ~ 50
	obsidianArmorDurabilityMultiplier = 29
	#Obsidian armor enchantability [1-31, default: 13]
	#Range: 1 ~ 31
	obsidianArmorEnchantability = 13
	#Obsidian armor toughness [0.0-4.0, default: 1.0]
	#Range: 0.0 ~ 4.0
	obsidianArmorToughness = 1.0
	#Obsidian armor knockback resistance [0.0-4.0, default: 0.0]
	#Range: 0.0 ~ 4.0
	obsidianArmorKnockbackResistance = 0.0
	#Obsidian armor protection head [1-50, default: 3]
	#Range: 1 ~ 50
	obsidianArmorProtectionHead = 3
	#Obsidian armor protection body [1-50, default: 8]
	#Range: 1 ~ 50
	obsidianArmorProtectionBody = 8
	#Obsidian armor protection leggings [1-50, default: 6]
	#Range: 1 ~ 50
	obsidianArmorProtectionLeggings = 6
	#Obsidian armor protection feet [1-50, default: 3]
	#Range: 1 ~ 50
	obsidianArmorProtectionFeet = 3

#Copper Armor Material
[copper_armor_material]
	#Copper armor durability multiplier [1-50, default: 14]
	#Range: 1 ~ 50
	copperArmorDurabilityMultiplier = 14
	#Copper armor enchantability [1-31, default: 13]
	#Range: 1 ~ 31
	copperArmorEnchantability = 13
	#Copper armor toughness [0.0-4.0, default: 0.0]
	#Range: 0.0 ~ 4.0
	copperArmorToughness = 0.0
	#Copper armor knockback resistance [0.0-4.0, default: 0.0]
	#Range: 0.0 ~ 4.0
	copperArmorKnockbackResistance = 0.0
	#Copper armor protection head [1-50, default: 2]
	#Range: 1 ~ 50
	copperArmorProtectionHead = 2
	#Copper armor protection body [1-50, default: 5]
	#Range: 1 ~ 50
	copperArmorProtectionBody = 5
	#Copper armor protection leggings [1-50, default: 4]
	#Range: 1 ~ 50
	copperArmorProtectionLeggings = 4
	#Copper armor protection feet [1-50, default: 2]
	#Range: 1 ~ 50
	copperArmorProtectionFeet = 2

#Amethyst Armor Material
[amethyst_armor_material]
	#Amethyst armor durability multiplier [1-50, default: 37]
	#Range: 1 ~ 50
	amethystArmorDurabilityMultiplier = 33
	#Amethyst armor enchantability [1-31, default: 25]
	#Range: 1 ~ 31
	amethystArmorEnchantability = 25
	#Amethyst armor toughness [0.0-4.0, default: 0.75]
	#Range: 0.0 ~ 4.0
	amethystArmorToughness = 0.75
	#Amethyst armor knockback resistance [0.0-4.0, default: 0.25]
	#Range: 0.0 ~ 4.0
	amethystArmorKnockbackResistance = 0.25
	#Amethyst armor protection head [1-50, default: 3]
	#Range: 1 ~ 50
	amethystArmorProtectionHead = 3
	#Amethyst armor protection body [1-50, default: 8]
	#Range: 1 ~ 50
	amethystArmorProtectionBody = 8
	#Amethyst armor protection leggings [1-50, default: 6]
	#Range: 1 ~ 50
	amethystArmorProtectionLeggings = 6
	#Amethyst armor protection feet [1-50, default: 3]
	#Range: 1 ~ 50
	amethystArmorProtectionFeet = 3

#Armor Full Set Bonus
[full_set_bonus]
	#Enable ruby armor fire protection [true / false]
	rubyFullSetBonus = false
	#Enable emerald armor water breathing [true / false]
	emeraldFullSetBonus = false
	#Enable amethyst armor no fall damage [true / false]
	amethystFullSetBonus = false

#Bow Zoom Value
[bow_zoom]
	#Bow zoom valuee [0.0-1.0, default: .45]
	#Range: 0.1 ~ 0.9
	bow_zoom_value = 0.45

#Full Damage
[full_damage]
	#3x3 tools take full damage [true / false]
	full_damage = false

