
#Settings for world gen (Doesn't work in 1.18.2. Use datapacks instead.)
["World Gen"]
	#Average chunk separation between companion houses
	#Range: > 11
	averageHouseSeparation = 20

["Companion config"]
	#Toggle friendly fire
	friendlyFire = false
	#Toggle fall damage for companions
	fallDamage = true

